env: development
replicaCount: 1

image:
  repository: docker.io/library
  pullPolicy: IfNotPresent

imagePullSecrets: []

resources:
  limits:
    cpu: 500m
    memory: 2G
  requests:
    cpu: 250m
    memory: 1.5G

app:
  javaToolOptions: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
  command:
    #entrypoint: <Unused parameter>
    args: []
  networking:
    ingress:
      host: "api.{{ cookiecutter.subdomain }}.{{ cookiecutter.domain }}.local"
      tls: false
      certManager: false
    port:
      http: "8080"
      debug: "8000"
    httpService:
      type: NodePort
      port: "8080"
      nodePort: "31000"
    debugService:
      type: NodePort
      port: "8000"
      nodePort: "31800"
