env: staging
replicaCount: 1

image:
  repository: 992382473777.dkr.ecr.ca-central-1.amazonaws.com
  pullPolicy: Always

imagePullSecrets:
  - name: regcred

resources:
  limits:
    cpu: 2000m
    memory: 2G
  requests:
    cpu: 1000m
    memory: 2G

app:
  javaToolOptions: "-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
  command:
    #entrypoint: <Unused parameter>
    args: []
  networking:
    ingress:
      host: "api.staging.{{ cookiecutter.domain }}.{{ cookiecutter.tld }}"
      tls: true
      certManager: true
    port:
      http: "8080"
      debug: "8000"
    httpService:
      type: NodePort
      port: "8080"
      nodePort: "31000"
    debugService:
      type: NodePort
      port: "8000"
      nodePort: "31800"
