services:
  bruno:
    build:
      context: ..
      dockerfile: bruno/bruno.dockerfile
    working_dir: /app
    environment:
      NODE_PATH: /usr/local/lib/node_modules:/app/bruno/node_modules
    volumes:
      - ../:/app
      - /app/bruno/node_modules
      - ${HOME}/.bru:/root/.bru


