/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface AddUserDto {
  userName: string;
  displayName: string;
  firstName: string;
  lastName: string;
  email: string;
  statusId: number;
  salutationId?: number;
  phoneNumber?: string;
  roleIds: number[];
  imageSrc?: string;
}
