/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type GetAllUsersParams = {
  ids?: number[];
  exclude_ids?: number[];
  user_names?: string[];
  display_names?: string[];
  emails?: string[];
  phone_numbers?: string[];
  status?: number[];
  salutations?: number[];
  roles?: string[];
  sort?: string[];
  order_asc?: boolean;
  page?: number;
  size?: number;
  attr?: string[];
};
