/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserSalutationDto } from "./userSalutationDto";

export interface PageDtoUserSalutationDto {
  content?: UserSalutationDto[];
  totalElements?: number;
  totalPages?: number;
}
