/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserRoleDto } from "./userRoleDto";

export interface PageDtoUserRoleDto {
  content?: UserRoleDto[];
  totalElements?: number;
  totalPages?: number;
}
