/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UnitDto } from "./unitDto";

export interface PageDtoUnitDto {
  content?: UnitDto[];
  totalElements?: number;
  totalPages?: number;
}
