/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface TenantDto {
  id?: string;
  name?: string;
  url?: string;
  isReady?: boolean;
  createdAt?: string;
  lastUpdated?: string;
}
