/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateUserDto {
  id?: number;
  userName?: string;
  displayName?: string;
  firstName?: string;
  lastName?: string;
  statusId?: number;
  salutationId?: number;
  phoneNumber?: string;
  imageSrc?: string;
  /**
   * @minItems 1
   * @maxItems 2147483647
   */
  roleIds?: number[];
  version: number;
}
