/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateUserRoleDto {
  id?: number;
  name?: string;
  version?: number;
}
