/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { IaasObjectStoreFileDto } from "./iaasObjectStoreFileDto";
import type { UserStatusDto } from "./userStatusDto";
import type { UserSalutationDto } from "./userSalutationDto";
import type { UserRoleDto } from "./userRoleDto";

export interface UserDto {
  id?: number;
  userName?: string;
  iaasUsername?: string;
  displayName?: string;
  firstName?: string;
  lastName?: string;
  email?: string;
  phoneNumber?: string;
  imageSrc?: string;
  objectStoreFile?: IaasObjectStoreFileDto;
  status?: UserStatusDto;
  salutation?: UserSalutationDto;
  roles?: UserRoleDto[];
  createdAt?: string;
  lastUpdated?: string;
  version?: number;
}
