/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UserSalutationDto {
  id?: number;
  title?: string;
  createdAt?: string;
  lastUpdated?: string;
  version?: number;
}
